### ISSUE TITLE
使用Segment分割头，怎么剪枝

### ISSUE THREAD

**Issue by yinheyu** [Cydia2018/YOLOv5-Light#4]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

请问使用Segment分割头，怎么剪枝？
报错：
     former = from_to_map[layername]
KeyError: 'model.24.proto.cv1.conv'

**Comment by Cydia2018** [comment]
可以参考 https://github.com/Cydia2018/YOLOv5-Light/blob/9ecbcda52d602f925d405f2c6ea654b087d83786/utils/prune_utils.py#L86 第86行类似改动

**Comment by yinheyu** [comment]
你好，我改动了啊，还是这个报错，求楼主帮我啊
 elif m in {Detect,Segment}:
            for j in range(3):
                ignore_idx.append(named_m_base + ".m.{}".format(j))
                from_to_map[named_m_base + ".m.{}".format(j)] = fromlayer[f[j]]
        else:
            fromlayer.append(fromlayer[-1])

Traceback (most recent call last):
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 115, in <module>
    prune_and_export(model, ignore_idx, opt)
  File "D:\YOLOv5-Light-main\pruning\slim.py", line 53, in prune_and_export
    weights_inheritance(model, compact_model, from_to_map, maskbndict)
  File "D:\YOLOv5-Light-main\utils\prune_utils.py", line 195, in weights_inheritance
    former = from_to_map[layername]
KeyError: 'model.24.proto.cv1.conv'

**Comment by yinheyu** [comment]
你好，我改动了啊，还是这个报错，求楼主帮我啊,跪求！



elif m in {Detect,Segment}:
for j in range(3):
ignore_idx.append(named_m_base + ".m.{}".format(j))
from_to_map[named_m_base + ".m.{}".format(j)] = fromlayer[f[j]]
else:
fromlayer.append(fromlayer[-1])

Traceback (most recent call last):
File "D:\YOLOv5-Light-main\pruning\slim.py", line 115, in
prune_and_export(model, ignore_idx, opt)
File "D:\YOLOv5-Light-main\pruning\slim.py", line 53, in prune_and_export
weights_inheritance(model, compact_model, from_to_map, maskbndict)
File "D:\YOLOv5-Light-main\utils\prune_utils.py", line 195, in weights_inheritance
former = from_to_map[layername]
KeyError: 'model.24.proto.cv1.conv'







我把yolov5s_slim.yaml文件的最后一行变成这样了，其他没有改动了。&nbsp;[[17, 20, 23], 1, Segment, [nc, anchors, 32, 256]],&nbsp; # Detect(P3, P4, P5)]





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cydia2018/YOLOv5-Light"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 中午11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Cydia2018/YOLOv5-Light] 使用Segment分割头，怎么剪枝 (Issue #4)





 
可以参考 https://github.com/Cydia2018/YOLOv5-Light/blob/9ecbcda52d602f925d405f2c6ea654b087d83786/utils/prune_utils.py#L86 第86行类似改动

**Comment by yinheyu** [comment]
无论是elif m in (Detect,Segment):   还是elif m is Segment   都不行啊
